#!/bin/bash
used_space=`df -h / | grep -v Filesystem | awk '{print $5}' | sed 's/%//g'`
#used_space=100
#echo $used_space
case $used_space in
  [0-9]|[1-6][0-9]|7[0-4]) echo "OK - $used_space% of disk space used.";exit 0;;  # 0-60
  7[5-9]|8[0-9]) echo "WARNING -  $used_space% of disk space used.";exit 1;; # 61-79
  9[0-9]|100) echo "CRITICAL - $used_space% of disk space used.";exit 2  ;;             # 80-100
  *) echo "UNKNOWN - $used_space% of disk space used.";exit 3;;                    # >100
esac