#!/bin/bash
ram=$(free -g | grep -v grep | grep Mem | awk {'print $3/$2 * 100.0'})
ram1=${ram%.*}
ram2=$(free -g | grep -v grep | grep Mem | awk {'print $3'})

case $ram1 in
  [0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]|6[0-9]|7[0-9]|8[0-9]) echo "OK - $ram1% RAM usage, $ram2 GB RAM space used.";exit 0;;  # 0-79%
#  8[0-9]) echo "WARNING -  $ram1% RAM usage, $ram2 GB RAM space used.";exit 1;; # 80-89%
  9[0-9]|100) echo "CRITICAL - $ram1% RAM usage, $ram2 GB RAM space used";exit 2  ;;             # 99-100%
  *) echo "UNKNOWN -  RAM space used.";exit 3;;                    # >15
esac
