#!/bin/bash
ram=$(free -g | grep -v grep | grep Mem | awk {'print $3'})
#echo $ram

case $ram in
  [0-9]|10) echo "OK - $ram GB of RAM used.";exit 0;;  # 0-10
  1[1-2]) echo "WARNING -  $ram GB RAM space used.";exit 1;; # 11-12
  1[3-5]) echo "CRITICAL - $ram GB of RAM space used.";exit 2  ;;             # 13-15
  *) echo "UNKNOWN -  RAM space used.";exit 3;;                    # >15
esac